### ISSUE TITLE
Cannot use custom registry

### ISSUE THREAD

**Issue by niconavarrete** [gotenxds/NpmPackageDownloader#5]
Registry url is hardcoded in npmApi.js, so no npmrc or --registry can be used
`return util.format("https://registry.npmjs.org/%s/-/%s-%s.tgz", name.replace('%2f', '/'), nameUtils.unscopeName(name), version);

return util.format("https://registry.npmjs.org/%s/", name.replace('/', '%2f'));`

**Comment by gotenxds** [comment]
Thank you, will fix over the weekend.
